<a href="https://colab.research.google.com/github/DrAlexSanz/NLP-SPEC-C2/blob/master/W2/POS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/DrAlexSanz/NLP-SPEC-C2/master/W2/WSJ_02-21.pos
!wget https://raw.githubusercontent.com/DrAlexSanz/NLP-SPEC-C2/master/W2/WSJ_24.pos
!wget https://raw.githubusercontent.com/DrAlexSanz/NLP-SPEC-C2/master/W2/hmm_vocab.txt
!wget https://raw.githubusercontent.com/DrAlexSanz/NLP-SPEC-C2/master/W2/test.words.txt
!wget https://raw.githubusercontent.com/DrAlexSanz/NLP-SPEC-C2/master/W2/utils_pos.py

--2020-10-07 19:47:54--  https://raw.githubusercontent.com/DrAlexSanz/NLP-SPEC-C2/master/W2/WSJ_02-21.pos
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8279089 (7.9M) [text/plain]
Saving to: ‘WSJ_02-21.pos’

WSJ_02-21.pos       100%[===================>]   7.90M  17.4MB/s    in 0.5s    

2020-10-07 19:47:55 (17.4 MB/s) - ‘WSJ_02-21.pos’ saved [8279089/8279089]

--2020-10-07 19:47:55--  https://raw.githubusercontent.com/DrAlexSanz/NLP-SPEC-C2/master/W2/WSJ_24.pos
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 286063 (279K) [text/plain]
Sa

In [2]:
import numpy as np
import pandas as pd

### Some information on tags
For this notebook you will be using a toy example including only three tags (or states). In a real world application there are many more tags which can be found here.

In [3]:
# Define corresponding tags

tags = ["RB", "NN", "TO"] # Tags are Adverb, Noun and TO (preposition)

In this week's assignment you will construct some dictionaries that provide useful information of the tags and words you will be working with.

One of these dictionaries is the transition_counts which counts the number of times a particular tag happened next to another. The keys of this dictionary have the form (previous_tag, tag) and the values are the frequency of occurrences.

Another one is the emission_counts dictionary which will count the number of times a particular pair of (tag, word) appeared in the training dataset.

In general think of transition when working with tags only and of emission when working with tags and words.

In this notebook you will be looking at the first one:

In [6]:
# Define transition_dict

transition_counts = {
    ("NN", "NN"): 16241,
    ("RB", "RB"): 2263,
    ("TO", "TO"): 2,
    ('NN', 'TO'): 5256,
    ('RB', 'TO'): 855,
    ('TO', 'NN'): 734,
    ('NN', 'RB'): 2431,
    ('RB', 'NN'): 358,
    ('TO', 'RB'): 200
    }

In [8]:
num_tags = len(tags)

transition_matrix = np.zeros((num_tags, num_tags))

In [10]:
# For consistency
sorted_tags = sorted(tags)
sorted_tags

['NN', 'RB', 'TO']

To fill this matrix with the correct values you can use a double for loop. You could also use itertools.product to one line this double loop:

In [11]:
for i in range(num_tags):

  for j in range(num_tags):
      tag_tuple = (sorted_tags[i], sorted_tags[j])

      transition_matrix[i, j] = transition_counts.get(tag_tuple)

print(transition_matrix)

[[1.6241e+04 2.4310e+03 5.2560e+03]
 [3.5800e+02 2.2630e+03 8.5500e+02]
 [7.3400e+02 2.0000e+02 2.0000e+00]]
